### ISSUE TITLE
Issue with new versions of download and upload artifacts

### ISSUE THREAD

**Issue by samuelpcabral** [joonvena/Robot-Reporter#19]
Hello, I updated the download and upload artifact to this versions:

actions/upload-artifact@v4
actions/download-artifact@v4.1.7

but I got this error:

Status: Downloaded newer image for joonvena/robot-reporter:v2.5
2024/09/23 15:04:59 open /home/runner/work/robotframework-aws/robotframework-aws/robot_reports/output.xml: no such file or directory
Error: Process completed with exit code 1.

need to update something or I need to change my code? 

this is my yml:

```
jobs:
  run-localstack-and-robot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose -y
    - name: Start Localstack docker
      working-directory: ./localstack
      run: |
        docker-compose up -d
    - name: Wait for LocalStack to be ready
      run: sleep 10
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      env:
        ROBOT_TESTS_DIR: ${{ github.workspace }}/Tests
        ROBOT_REPORTS_DIR: ${{ github.workspace }}/reports
      with:
        python-version: '3.10'
    - name: Install Dependencies
      working-directory: ./
      run: pip install -r requirements.txt
    - name: Run Robot Framework
      run: robot -d ./reports ./tests/robot
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: robot_reports
        path: reports

  generate-robot-report:
    if: always()
    needs: [ run-localstack-and-robot ]
    runs-on: ubuntu-latest
    steps:
      - name: Download reports
        uses: actions/download-artifact@v4.1.7
        with:
          name: robot_reports
      - name: Send report to commit
        uses: joonvena/robotframework-reporter-action@v2.5
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          report_path: /robot_reports
```

here the full github action: https://github.com/samuelpcabral/robotframework-aws/actions/runs/10997037190/job/30531740457
