### ISSUE TITLE
No such file or directory /github/workspace/assets/template.txt

### ISSUE THREAD

**Issue by shanebenlolo** [joonvena/Robot-Reporter#4]
I received the following error when using your `robotframework-reporter-action@v0.1`: 

`2021/07/15 23:04:52 stat /github/workspace/assets/template.txt: no such file or directory`

here is the full action: 
```
      - name: Send test report as comment to commit
        uses: joonvena/robotframework-reporter-action@v0.1
        if: ${{ github.event_name == 'push' }}
        env:
          GH_ACCESS_TOKEN: ${{ github.TOKEN }}
          REPO_OWNER: ${{ github.REPOSITORY_OwNER }}
          COMMIT_SHA: ${{ github.SHA }}
          REPOSITORY: ${{ github.repository }}
          REPORT_PATH: ${{ github.workspace }}/Reports
```

please let me know if you know what the issue is, thank you 👍
